# Generated by Django 5.1.7 on 2025-03-12 06:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book_copies', '0002_alter_bookcopy_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookLending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(max_length=100)),
                ('borrower_email', models.EmailField(max_length=254)),
                ('borrower_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('returned_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('avtive', 'Active'), ('returned', 'Returned'), ('overdue', 'Overdue')], default='avtive', max_length=100)),
                ('book_copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_lending', to='book_copies.bookcopy')),
            ],
        ),
    ]
